Aofeng/Aofeng/Controllers/ActiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Business;
using Oaww.Utility;
using Oaww.Entity;
using Oaww.ViewModel;
using System.Configuration;
using System.IO;

namespace Aofeng.Controllers
{
    public class ActiveController : BaseController
    {
        CommonService _commonService = new CommonService();
        MessageService _service = new MessageService(11);
        // GET: Active
        public ActionResult Index(string itemid, string mid, int nowpage = 0, int jumpPage = 0, int? group = -1, string classType = "large")
        {
            if (nowpage == 0 && jumpPage != 0)
            {
                nowpage = jumpPage;
            }
            else if (nowpage == 0 && jumpPage == 0)
            {
                nowpage = 1;
            }
            if (string.IsNullOrEmpty(itemid))
            {
                return RedirectToAction("Index", "Home");
            }

            MessageViewModel model = new MessageViewModel() { mid = mid, itemid = itemid, group = group, classType = classType };
            if (group == -1)
            {
                group = null;
            }
            model.ListGroupMessage = _service.GetVaildGroupMessages(itemid);
            model.ListGroupMessage.Insert(0, new GroupMessage() { ID = -1, Group_Name = "全部" });
            model.ListActiveDateRange = _service.GetActiveDateRangeALL(itemid);
            MessageUnitSetting messageUnitSetting = (MessageUnitSetting)ViewBag.UnitSetting;
            int ShowCount = messageUnitSetting.ShowCount.HasValue ? messageUnitSetting.ShowCount.Value : 10; //沒有預設10
            ViewBag.UnitSetting = new MessageUnitSetting();

            Menu menu = _commonService.GetMenuByMid(mid);

            #region Grid

            var paging = _service.GetPaging(itemid, group, "", nowpage, ShowCount);

            model.ListMessageItem = paging.rows;

            //Grid一定要有
            ViewBag.Total = paging.total;
            ViewBag.ShowCount = ShowCount;
            ViewBag.NowPage = nowpage;
            #endregion

            ViewBag.BoxClass = "news_box";

            return View(model);
        }
        public ActionResult MessageView(string itemid, string mid, string GroupName, bool isPrint = false)
        {
            ViewBag.print = isPrint;

            MessageViewModel model = new MessageViewModel() { mid = mid };

            model.MessageItem = _service.GetMessageItemByID(itemid);

            model.GroupName = _service.GetGroupName(model.MessageItem.GroupID.Value);

            model.ListMessageFile = _service.GetFileDownloadFiles(itemid);
            model.ListMessageImage = _service.GetFileDownloadImages(itemid);
            ViewBag.PublishDate = model.MessageItem.PublicshDate.Value.ToString("yyyy/MM/dd");
            ViewBag.BoxClass = "inner_box";


            ViewBag.modelName = model.MessageItem.Title;
            model.ListActiveDateRange = _service.GetActiveDateRange(itemid);
            //FB Image
            UrlHelper helper = new UrlHelper(Request.RequestContext);
            var urlBuilder = new System.UriBuilder(Request.Url.AbsoluteUri) { Path = helper.Content("~/UploadImage/MessageItem/" + model.MessageItem.RelateImageFileName), Query = null, };
            ViewBag.ImageUrl = model.MessageItem.RelateImageFileName.IsNullOrEmpty() ? "" : urlBuilder.ToString();
            ViewBag.FBContent = model.MessageItem.HtmlContent.StripHTML().Replace("\n", "").Replace("\t", "");

            return View(model);
        }

        public ActionResult FileDownLoad2(string modelid, string itemid)
        {
            var model = _service.GetMessageItemByID(itemid);
            string filepath = model.UploadFilePath;
            string oldfilename = model.UploadFileName;
            var uploadfilepath = ConfigurationManager.AppSettings["UploadFile"];
            if (uploadfilepath.IsNullOrEmpty())
            {
                uploadfilepath = Request.PhysicalApplicationPath + "\\UploadFile";
            }
            if (filepath != "")
            {
                string filename = System.IO.Path.GetFileName(filepath);
                if (string.IsNullOrEmpty(oldfilename)) { oldfilename = filename; }
                Stream iStream = new FileStream(uploadfilepath + filepath, FileMode.Open, FileAccess.Read, FileShare.Read);
                return File(iStream, "application/octet-stream", oldfilename);
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
    }
}

Aofeng/Aofeng/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Business;
using Oaww.ViewModel;
using System.Net.Mail;
using System.Text.RegularExpressions;
using Oaww.Utility;
using CaptchaMvc.HtmlHelpers;
using System.ComponentModel.DataAnnotations;

namespace Aofeng.Controllers
{
    public class CommonController : BaseController
    {
        CommonService _commonService = new CommonService();
        public ActionResult Forward(string Url, string Name, string sender = "", string sender_mail = "", string receive_email = "", string message = "", string btn = "")
        {
            ForwardViewModel model = new ForwardViewModel();

            model.Url = HttpUtility.UrlDecode(Url);
            model.Name = HttpUtility.UrlDecode(Name);
            model.sender = sender;
            model.sender_mail = sender_mail;
            model.receive_email = receive_email;
            model.message = message;
            model.btn = btn;

            ViewBag.BoxClass = "inner_box page";
            ViewBag.mid = "Forward";
            return View(model);
        }

        public ActionResult Forward_OK(string Url, string Name, string sender, string sender_mail, string receive_email, string message)
        {
            Regex regex = new Regex(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$");
            var echeck = new EmailAddressAttribute();
            string result = string.Empty;
            if(sender.IsNullOrEmpty())
            {
                return RedirectToAction("Forward", new { @Url = Url, @Name = Name, @sender = sender, @sender_mail = sender_mail, @receive_email = receive_email, @message = message, @btn = "sender" });
            }
            else if(sender_mail.IsNullOrEmpty())
            {
                return RedirectToAction("Forward", new { @Url = Url, @Name = Name, @sender = sender, @sender_mail = sender_mail, @receive_email = receive_email, @message = message, @btn = "sender_mail" });
            }
            else if (echeck.IsValid(sender_mail) == false)
            {
                return RedirectToAction("Forward", new { @Url = Url, @Name = Name, @sender = sender, @sender_mail = sender_mail, @receive_email = receive_email, @message = message, @btn = "sender_mail_E" });
            }
            else if (receive_email.IsNullOrEmpty())
            {
                return RedirectToAction("Forward", new { @Url = Url, @Name = Name, @sender = sender, @sender_mail = sender_mail, @receive_email = receive_email, @message = message, @btn = "receive_email" });
            }          
            else if (echeck.IsValid(receive_email) == false)
            {
                return RedirectToAction("Forward", new { @Url = Url, @Name = Name, @sender = sender, @sender_mail = sender_mail, @receive_email = receive_email, @message = message, @btn = "receive_email_E" });        
            }
            else if(!this.IsCaptchaValid("驗證失敗！"))
            {
                return RedirectToAction("Forward", new { @Url = Url, @Name = Name, @sender = sender, @sender_mail = sender_mail, @receive_email = receive_email, @message = message, @btn = "Captcha" });
            }
            else
            {
                try
                {

                    SmtpClient smtp = CommonFun.GetSMTPClient();
                    MailMessage msg = new MailMessage();
                    msg.From = new MailAddress(sender_mail, sender);
                    msg.Subject = $"您的朋友 【{sender}】 轉寄中華穀類這個網站連結給您。與您分享！";
                    msg.BodyEncoding = System.Text.Encoding.UTF8;
                    msg.IsBodyHtml = true;

                    msg.Body = message + "<br/>" + HttpUtility.UrlDecode(Url);

                    foreach (string m in receive_email.Split(';'))
                    {
                        msg.To.Add(new MailAddress(m));
                    }
                    smtp.Send(msg);

                    result = "轉寄好友寄送成功";
                }
                catch (Exception ex)
                {
                    result = "轉寄好友寄送失敗"+ ex;
                }

                ViewBag.result = result;
                ViewBag.mid = "Forward";

                return View();
            }
        }

        
    }
}

Aofeng/Aofeng/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Business;
using Oaww.Entity;
using Oaww.ViewModel;
using System.Configuration;
using System.IO;
using Oaww.Utility;
using System.Text.RegularExpressions;
using Newtonsoft.Json;

namespace Aofeng.Controllers
{
    public class FormController : BaseController
    {
        FormService _Service = new FormService();

        // GET: Form
        public ActionResult Index(string itemid,string mid)
        {
            if (string.IsNullOrEmpty(itemid)|| string.IsNullOrEmpty(mid))
            {
                return RedirectToAction("Index", "Home");
            }
            FormViewModel model = new FormViewModel() { mid = mid, itemid = itemid};
            
            model.FormSetting = _Service.GetItemFormSetting(itemid);
            model.formSelItems = _Service.GetListFormSelItem(itemid);
            Dictionary<string, string> json = new Dictionary<string, string>();

            if (Session["json"] != null)
            {
                json = (Dictionary<string, string>)Session["json"];

                Session["json"] = null;
            }

            model.formSelItems.ForEach(t =>
            {
                if (json != null && json.ContainsKey(t.ID.ToString()))
                {
                    t.DefaultText = json[t.ID.ToString()];
                }
                else
                {
                    t.DefaultText = t.DefaultText;
                }
            });
            ViewBag.itemid = itemid;
            ViewBag.mid = mid;

            return View(model);
        }

        public ActionResult SaveForm(string itemid, string mid)
        {
            Session["ErrorMessage"] = "";
            string jsonstr = string.Empty;
            string btn = string.Empty;

            Dictionary<string, string> json = new Dictionary<string, string>();
            List<FormSelItem> ListFormSelItem = _Service.GetListFormSelItem(itemid);
            string ErrorMessage = string.Empty;

            ListFormSelItem.OrderBy(t=>t.ID).ToList().ForEach(t =>
            {
                if (Request[t.ID.ToString()] != null)
                {
                    json.Add(t.ID.ToString(), Request[t.ID.ToString()]);
                }

                if (t.MustInput && (Request[t.ID.ToString()] == null || Request[t.ID.ToString()].IsNullOrEmpty()))
                {
                    ErrorMessage += t.Title + "不得為空白！ <br/>";
                    btn = t.ID.ToString();
                    
                }


                if (t.Title.ToUpper().Replace("-", "") == "EMAIL" && (Request[t.ID.ToString()] != null && Request[t.ID.ToString()].IsNullOrEmpty() == false))
                {
                    Regex regex = new Regex(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$");
                    Match match = regex.Match(Request[t.ID.ToString()].ToString());

                    if (match.Success == false)
                    {
                        ErrorMessage += t.Title + "格式錯誤！ <br/>";
                        btn = t.ID.ToString()+"Express";
                    }
                }
            });

            Session["json"] = json;

            if (ErrorMessage.IsNullOrEmpty() == false)
            {
                Session["ErrorMessage"] = ErrorMessage;
                return RedirectToAction("Index", new { mid = mid, itemid = itemid});
            }

            //if (!this.IsCaptchaValid("驗證失敗！") && (itemid == "1" || itemid =="2"))
            //{
            //    Session["ErrorMessage"] = "驗證碼失敗，請重新輸入！";
            //    btn = "Captcha";

            //    return RedirectToAction("Index", new { mid = mid, itemid = itemid});
            //}

            string result = _Service.SaveForm(JsonConvert.SerializeObject(json, Formatting.None), json, itemid);

            //if(itemid == "1" || itemid == "2")
            //{
                if (result == "輸入失敗")
                {
                    Session["ErrorMessage"] = "輸入失敗！";

                    return RedirectToAction("Index", new { mid = mid, itemid = itemid, first = false, btn = btn });
                }
                else
                {
                    Session["json"] = null;

                    Session["ErrorMessage"] = result;
                    return RedirectToAction("ConfirmContent", new { mid = mid, itemid = itemid });
                }
            //}
            //else
            //{
            //    return Json(result);
            //}
        }
        public ActionResult ConfirmContent(string mid, string itemid)
        {
            FormSetting formSetting = _Service.GetItemFormSetting(itemid);
            return View(formSetting);
        }
    }
}

Aofeng/Aofeng/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Business;
using Oaww.Utility;
using Oaww.Entity;
using System.Configuration;
using System.IO;
namespace Aofeng.Controllers
{
    public class PageController : BaseController
    {
        PageService _service = new PageService(1);
        public ActionResult Index(string itemid, string mid, bool print = false)
        {
            ViewBag.print = print;

            if (itemid.IsNullOrEmpty() || mid.IsNullOrEmpty()) { return RedirectToAction("Index", "Home"); }

            PageIndexItem PageIndexItem = _service.GetVaildPageIndexItemByItemID(itemid,this.LanguageID);

            if (PageIndexItem == null || PageIndexItem.HtmlContent == null)
            {
                return RedirectToAction("Index", "Home");
            }

            PageIndexItem.HtmlContent = HttpUtility.HtmlDecode(PageIndexItem.HtmlContent);

            ViewBag.PublishDate = "最近更新日期 :" + (PageIndexItem.UpdateDatetime.HasValue ? PageIndexItem.UpdateDatetime.Value.ToString("yyyy/MM/dd") : PageIndexItem.CreateDatetime.Value.ToString("yyyy/MM/dd"));

            ViewBag.BoxClass = "inner_box";

            //FB Image
            UrlHelper helper = new UrlHelper(Request.RequestContext);
            var urlBuilder = new System.UriBuilder(Request.Url.AbsoluteUri) { Path = helper.Content("~/UploadImage/PageEdit/" + PageIndexItem.ImageFileName), Query = null, };
            ViewBag.ImageUrl = PageIndexItem.ImageFileName.IsNullOrEmpty() ? "" : urlBuilder.ToString();
            ViewBag.FBContent = PageIndexItem.HtmlContent.StripHTML().Replace("\n", "").Replace("\t", "");

            return View(PageIndexItem);
        }

        public ActionResult FileDownLoad2(string modelid, string itemid)
        {
            var model = _service.GetModelByID(modelid, itemid);
            string filepath = model.UploadFilePath;
            string oldfilename = model.UploadFileName;
            var uploadfilepath = ConfigurationManager.AppSettings["UploadFile"];
            if (uploadfilepath.IsNullOrEmpty())
            {
                uploadfilepath = Request.PhysicalApplicationPath + "\\UploadFile";
            }
            if (filepath != "")
            {
                string filename = System.IO.Path.GetFileName(filepath);
                if (string.IsNullOrEmpty(oldfilename)) { oldfilename = filename; }
                Stream iStream = new FileStream(uploadfilepath + filepath, FileMode.Open, FileAccess.Read, FileShare.Read);
                return File(iStream, "application/octet-stream", oldfilename);
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
    }
}

Aofeng/Aofeng/Views/Shared/Captcha.cshtml
@{
    Layout = null;
}
@model CaptchaMvc.Models.DefaultBuildInfoModel
@{
    string id = Guid.NewGuid().ToString("N");
    string functionName = string.Format("______{0}________()", Guid.NewGuid().ToString("N"));
    <script type="text/javascript">

        $(function () {
            $('#@id').show();
    });


    function @functionName {
            $('#@id').hide();
             $.post("@Model.RefreshUrl", { @Model.TokenParameterName: $('#@Model.TokenElementId').val() },
            function () {
                $('#@id').show();
            });
        return false;
    }
    </script>


}
<div class="input-group" style="width:100%;">
    @if (Model.IsRequired)
    {
        @Html.TextBox(Model.InputElementId, null, new Dictionary<string, object>
                                                      {
                                                          {"data-val", "true"},
                                                          {"data-val-required", Model.RequiredMessage},
                                                          {"class","input_code" },
                                                          {"placeholder","請輸入驗證碼" }
                                                      })
    }
    else
    {
        @Html.TextBox(Model.InputElementId, null, new { @class = "input_code", @onkeypress = "Captcha(event)", @placeholder = "請輸入驗證碼" })
    }

    <img id="@Model.ImageElementId" style="width:100px;height:40px;margin:0px;" src="@Model.ImageUrl" />
    <a href="#" id="@id" onclick="@functionName"><i class="fa fa-refresh"></i></a>
    @if (ViewData["submitBtn"] != null && ViewData["submitBtn"].ToString() == "Captcha")
    {
        <div class="required">@("請輸入驗證碼".GetLang())</div>
    }

    @Html.Hidden(Model.TokenElementId, Model.TokenValue)

    @Html.ValidationMessage(Model.InputElementId)
</div>

Aofeng/Aofeng/Views/Shared/_Link.cshtml
@using Oaww.HtmlHelp;
@using Oaww.Entity;

@{
    Layout = null;

    List<Menu> TopMenu = (List<Menu>)ViewBag.AllMenu;
    string mid = (string)ViewBag.mid;

    Menu menu = TopMenu.Where(t => t.ID.ToString() == mid).FirstOrDefault(); //先找到level

    //由上方/下方Menu來的
    if (menu == null)
    {
        List<Menu> DownMenu = (List<Menu>)ViewBag.DownMenu;
        menu = DownMenu.Where(t => t.ID.ToString() == mid).FirstOrDefault(); //先找到level
        if (menu != null)
        {
            menu = TopMenu.Where(t => t.ModelID == menu.ModelID && t.ModelItemID == menu.ModelItemID).FirstOrDefault();
        }
        else
        {
            List<Menu> UpMenu = (List<Menu>)ViewBag.UpMenu;
            menu = UpMenu.Where(t => t.ID.ToString() == mid).FirstOrDefault(); //先找到level
            if (menu != null)
            {
                menu = TopMenu.Where(t => t.ModelID == menu.ModelID && t.ModelItemID == menu.ModelItemID).FirstOrDefault();
            }
        }

    }

    int menuLevel = menu != null ? menu.MenuLevel : 1;



    //再找到1stMenu
    Menu Menu1st = new Menu();
    Menu menu2nd = new Menu();
    if (menuLevel == 1)
    {
        Menu1st = menu;
    }
    else if (menuLevel == 2)
    {
        Menu1st = TopMenu.Where(t => t.ID == menu.ParentID).First();
    }
    else if (menuLevel == 3)
    {
        menu2nd = TopMenu.Where(t => t.ID == menu.ParentID).First();
        Menu1st = TopMenu.Where(t => t.ID == menu2nd.ParentID).First();
    }

    if (ViewBag.mid == "Forward")
    {
        Menu1st = new Menu() { MenuName = "mail分享" };
    }

    if (ViewBag.mid == "Search")
    {
        if ((int)ViewBag.Language == 1)
        {
            Menu1st = new Menu() { MenuName = "搜尋結果" };
        }
        else
        {
            Menu1st = new Menu() { MenuName = "result" };
        }
    }
}

<a href="javascript:void(0);" title="主要內容區" accesskey="C" id="main-content">:::</a>
<a href="@Url.Action("Index","Home")"><i class="fa fa-home" aria-hidden="true"></i> </a>
<i class="fa fa-angle-right" aria-hidden="true"></i>

@if (Menu1st.LinkMode == 2 && menuLevel!=1)
{
    var m = Menu1st.ModelID;
    if (m == 1)
    {
        <a href="@Url.Action("Index","Page",new {itemid=Menu1st.ModelItemID,mid=Menu1st.ID })">@Menu1st.MenuName</a>
    }
    else if (m == 2)
    {
        <a href="@Url.Action("Index","Message",new {itemid=Menu1st.ModelItemID,mid=Menu1st.ID })">@Menu1st.MenuName</a>
    }
    else if (m == 3)
    {
        <a href="@Url.Action("Index","FileDownload",new {itemid=Menu1st.ModelItemID,mid=Menu1st.ID })">@Menu1st.MenuName</a>
    }
    else if (m == 4)
    {
        <a href="@Url.Action("Index","Form",new {itemid=Menu1st.ModelItemID,mid=Menu1st.ID })">@Menu1st.MenuName</a>
    }
    else if (m == 11)
    {
        <a href="@Url.Action("Index","Active",new {itemid=Menu1st.ModelItemID,mid=Menu1st.ID })">@Menu1st.MenuName</a>
    }
    else if (m == 12)
    {
        <a href="@Url.Action("Index","EPaper",new {itemid=Menu1st.ModelItemID,mid=Menu1st.ID })">@Menu1st.MenuName</a>
    }
}
else
{
    @Menu1st.MenuName
}
@if (menuLevel == 2)
{
    var m = menu.ModelID;
    <i class="fa fa-angle-right" aria-hidden="true"></i>
    <span class="active">

        @if (menu.LinkMode == 2)
        {

            if (m == 1)
            {
                <a href="@Url.Action("Index","Page",new {itemid=menu.ModelItemID,mid=menu.ID })">@menu.MenuName</a>
            }
            else if (m == 2)
            {
                <a href="@Url.Action("Index","Message",new {itemid=menu.ModelItemID,mid=menu.ID })">@menu.MenuName</a>
            }
            else if (m == 3)
            {
                <a href="@Url.Action("Index","FileDownload",new {itemid=menu.ModelItemID,mid=menu.ID })">@menu.MenuName</a>
            }
            else if (m == 4)
            {
                <a href="@Url.Action("Index","Form",new {itemid=menu.ModelItemID,mid=menu.ID })">@menu.MenuName</a>
            }
            else if (m == 11)
            {
                <a href="@Url.Action("Index","Active",new {itemid=menu.ModelItemID,mid=menu.ID })">@menu.MenuName</a>
            }
            else if (m == 12)
            {
                <a href="@Url.Action("Index","EPaper",new {itemid=menu.ModelItemID,mid=menu.ID })">@menu.MenuName</a>
            }
        }
        else
        {
            @menu.MenuName
        }

    </span>
}
@if (menuLevel == 3)
{
    var m = menu2nd.ModelID;
    <i class="fa fa-angle-right" aria-hidden="true"></i>
    <span class="active">
        @if (menu2nd.LinkMode == 2)
        {
            if (m == 1)
            {
                <a href="@Url.Action("Index","Page",new {itemid=menu2nd.ModelItemID,mid=menu2nd.ID })">@menu2nd.MenuName</a>
            }
            else if (m == 2)
            {
                <a href="@Url.Action("Index","Message",new {itemid=menu2nd.ModelItemID,mid=menu2nd.ID })">@menu2nd.MenuName</a>
            }
            else if (m == 3)
            {
                <a href="@Url.Action("Index","FileDownload",new {itemid=menu2nd.ModelItemID,mid=menu2nd.ID })">@menu2nd.MenuName</a>
            }
            else if (m == 4)
            {
                <a href="@Url.Action("Index","Form",new {itemid=menu2nd.ModelItemID,mid=menu2nd.ID })">@menu2nd.MenuName</a>
            }
            else if (m == 11)
            {
                <a href="@Url.Action("Index","Active",new {itemid=menu2nd.ModelItemID,mid=menu2nd.ID })">@menu2nd.MenuName</a>
            }
            else if (m == 12)
            {
                <a href="@Url.Action("Index","EPaper",new {itemid=menu2nd.ModelItemID,mid=menu2nd.ID })">@menu2nd.MenuName</a>
            }
        }
        else
        {
            @menu2nd.MenuName
        }
    </span>
    <i class="fa fa-angle-right" aria-hidden="true"></i>
    <span class="active">
        @menu.MenuName
    </span>
}

Aofeng/Aofeng/Views/Shared/_Page_Top.cshtml
@{
    Layout = null;

    UnitSetting unitSetting = (UnitSetting)ViewBag.UnitSetting;
}
    <div class="page_top_right">
        @if (unitSetting.IsForward)
        {
            <a href="@Url.Action("Forward","Common",new {@Url = HttpUtility.UrlEncode(ViewBag.Url),@Name=HttpUtility.UrlEncode(ViewBag.modelName) })" title="@("MAIL分享".GetLang())" target="_blank"><img src="@Url.Content("~/Content/img/icon_mail.png")" alt="轉寄好友"></a>
        }
        @if (unitSetting.IsPrint)
        {
            <a href="@ViewBag.PrintUrl" title="@("列印本頁".GetLang())" target="_blank"><img src="@Url.Content("~/Content/img/icon_print.png")" alt="友善列印"></a>

        }
        @if (unitSetting.IsShare)
        {
            <a href="javascript: void(window.open('http://www.facebook.com/share.php?u='.concat(encodeURIComponent(location.href)) ));" title="@("分享至 Facebook[另開新視窗]".GetLang())" target="_self"><img src="@Url.Content("~/Content/img/icon_facebook.png")" alt="facebook分享(另開新視窗)"></a>
            <a href="javascript: void(window.open('http://twitter.com/home/?status='.concat(encodeURIComponent(document.title)) .concat(' ') .concat(encodeURIComponent(location.href))));" title="@("分享至 twitter[另開新視窗]".GetLang())" target="_self"><img src="@Url.Content("~/Content/img/icon_twitter.png")" alt="twitter分享(另開新視窗)"></a>
            <a href="http://plurk.com/?qualifier=shares&status=[分享]@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="@("分享至 plurk[另開新視窗]".GetLang())"><img src="@Url.Content("~/Content/img/icon_plurk.png")" alt="plurk分享(另開新視窗)"></a>
        }
    </div>