webadmin/Areas/webadmin/Controllers/EPaperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Filter;
using Oaww.ViewModel;
using Oaww.ViewModel.Search;
using Oaww.Entity;
using Oaww.Entity.SET;
using Oaww.Business;
using Oaww.Utility;
using System.Configuration;
using System.IO;
using NPOI.SS.Formula.Functions;

namespace Template.webadmin.Areas.webadmin.Controllers
{
    public class EPaperController : MenuController
    {
        protected CommonService _commonService = new CommonService();
        protected EPaperService _service;
        protected int _ModelID = 12;
        protected SET_EPAPER SET_EPAPER = new SET_EPAPER();


        private SET_BASE SET_BASE;
        private SET_MENU SET_MENU;
        //增加電子報模組
        MenuService _menuService = new MenuService();

        public EPaperController()
        {
            SET_EPAPER = _commonService.GetGeneral<SET_EPAPER>("M_EPAPER01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } });
            _service = new EPaperService(_ModelID);
            SET_BASE = _commonService.GetGeneral<SET_BASE>();
            SET_MENU = _commonService.GetGeneral<SET_MENU>("M_Menu01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } });

        }
        public EPaperController(int ModelID = 12)
        {
            SET_EPAPER = _commonService.GetGeneral<SET_EPAPER>("M_EPAPER01=@ID", new Dictionary<string, string>() { { "ID", ModelID.ToString() } });
            _service = new EPaperService(ModelID);
            _ModelID = ModelID;
            SET_BASE = _commonService.GetGeneral<SET_BASE>();
            SET_MENU = _commonService.GetGeneral<SET_MENU>("M_Menu01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } });

        }

        [AuthFilter(_FuncionID = "EPaper/Index")]
        public ActionResult Index()
        {
            ViewBag.Title = SET_EPAPER.M_EPAPER05;
            ViewBag.Link = SET_EPAPER.M_EPAPER06;

            return View();
        }


        [HttpPost]
        public ActionResult SetMainDelete(string[] idlist, string delaccount)
        {
            
                List<EPaperItem> EPaperItem = _service.GetEPaperItems(idlist);

                string result = _service.Delete(idlist, delaccount, this.LanguageID, this.Account, this.UserName);

                //if (result == "刪除成功")
                //{
                //    var oldroot = System.Web.HttpContext.Current.Request.PhysicalApplicationPath + $"\\UploadImage\\{SET_EPAPER.M_EPAPER02}\\";

                //    foreach (var items in EPaperItem)
                //    {
                //        //刪除File
                //        if (items.UploadFileName.IsNullOrEmpty() == false)
                //        {
                //            items.UploadFilePath = System.Web.HttpContext.Current.Request.PhysicalApplicationPath + "\\UploadFile" + items.UploadFilePath;

                //            if (System.IO.File.Exists(items.UploadFilePath))
                //            {
                //                System.IO.File.Delete(items.UploadFilePath);
                //            }
                //        }
                //        if (items.ImageFileName.IsNullOrEmpty() == false)
                //        {

                //            if (System.IO.File.Exists(oldroot + "\\" + items.ImageFileName))
                //            {
                //                System.IO.File.Delete(oldroot + "\\" + items.ImageFileName);
                //            }
                //        }


                //    }


                //}

                return Content(result);
           
        }


        //電子報模組呈現
        public ActionResult PagingMain(SearchModelBase model)
        {
            model.LangId = this.LanguageID;
            return Json(_service.Paging(model, _ModelID));
        }

        //電子報排序
        public ActionResult EditSeq(int? id, int seq, string type)
        {
            ModelEPaperMain ModelEpaperMain = _service.GetModelEPaperMain(id.ToString(), this.LanguageID);

            string result = _commonService.UpdateSeq<ModelEPaperMain>(id.Value, seq, this.LanguageID, this.Account, this.UserName, _ModelID);


            return Json(result);
        }


        //增加電子報模組
        public ActionResult EditUnit(string mainid, string name)
        {

            var str = "";
            if (mainid == "-1" || string.IsNullOrEmpty(mainid))
            {


                str = _menuService.AddUnit<ModelEPaperMain>(name, this.LanguageID, this.Account, _ModelID) && _service.SaveToColumnSetting(_ModelID) ? "新增成功" : "新增失敗";


            }
            else
            {

                str = _menuService.UpdateUnit<ModelEPaperMain>(name, mainid, this.Account, _ModelID.ToString()) ? "修改成功" : "修改失敗";

            }
            return Json(str);

        }

        public ActionResult ModelItem(string menuindex, string mainid, bool admin = false)
        {
            mainid = mainid.AntiXss();

            if (mainid.IsNullOrEmpty()) { return RedirectToAction("Index"); }


            var grouplist = _commonService.GetAllGroupSelectList<GroupEPaper>(mainid, int.Parse(this.LanguageID));
            grouplist.Insert(0, new System.Web.Mvc.SelectListItem() { Text = "全部", Value = "" });
            ViewBag.grouplist = grouplist;
            ViewBag.mainid = mainid.AntiXss();
            ViewBag.admin = admin;
            var maindata = _service.GetModelEPaperMain(mainid, this.LanguageID);

            if (maindata.ID > 0) { ViewBag.Title = maindata.Name; }

            ViewBag.SET_BASE = SET_BASE;
            ViewBag.SET_MENU = SET_MENU;
            ViewBag.SET_EPAPER = SET_EPAPER;


            return View("~/Areas/webadmin/Views/EPaper/ModelItem.cshtml");
        }




        //GROUP 在DATATABLE顯示
        public ActionResult PagingGroup(SearchModelBase model)
        {
            return Json(_commonService.PagingGroup<GroupEPaper>(model, int.Parse(this.LanguageID)));
        }

        public ActionResult GroupEdit(string mainid)
        {
            mainid = mainid.AntiXss();

            ViewBag.mainid = mainid;

            var maindata = _service.GetModelEPaperMain(mainid, this.LanguageID);

            if (maindata.ID > 0) { ViewBag.ModelItemTitle = maindata.Name; }


            return View("~/Areas/webadmin/Views/EPaper/GroupEdit.cshtml");
        }


        //排序GROUP(SORT)
        public ActionResult EditGroupSeq(int? id, int seq, string mainid)
        {
            GroupEPaper modelAMLMain = _service.GetGroupEPaperByID(id.ToString());

            string result = _commonService.UpdateGroupSeq<GroupEPaper>(id.Value, seq, mainid, this.Account, this.UserName);



            return Json(result);
        }

        //刪除GROUP
        public ActionResult SetGroupDelete(string[] idlist, string delaccount, string type)
        {
            string result = _commonService.DeleteGroup<GroupEPaper, EPaperItem>(idlist, delaccount, this.Account, this.UserName);

            return Content(result);
        }


        public ActionResult EditGroup(string name, string id, string mainid)
        {
            if (id == "-1" || id.IsNullOrEmpty())
            {
                string result = _commonService.EditGroupEPaper<GroupEPaper>(name, id, mainid, this.Account, int.Parse(this.LanguageID));

                return Json(result);
            }
            else
            {
                GroupEPaper groupAML = _service.GetGroupEPaperByID(id);

                string result = _commonService.EditGroupEPaper<GroupEPaper>(name, id, mainid, this.Account, int.Parse(this.LanguageID));

                return Json(result);
            }

        }

        public ActionResult PagingItem(EPaperSearchModel model)
        {
            model.LangId = this.LanguageID;
            return Json(_service.PagingItem(model, model.ModelID.ToString()));
        }


        public ActionResult EPaperEdit(string mainid, string itemid = "-1")
        {
            ViewBag.isview = Request["isview"] == null ? "" : Request["isview"].ToString().AntiXss();
            if (mainid.IsNullOrEmpty()) { return RedirectToAction("Index"); }
            EPaperEditModel model = null;
            ViewBag.grouplist = _commonService.GetAllGroupSelectList<GroupEPaper>(mainid, int.Parse(this.LanguageID));
            ViewBag.GroupID = new SelectList(ViewBag.grouplist, "GroupID", "Group_Name");
            ViewBag.mainid = mainid;
            var EPaperItemdata = _service.GetEPaperItemByID(itemid);

            if (EPaperItemdata.ItemID > 0) { ViewBag.Title = EPaperItemdata.Title; }

            var maindata = _service.GetModelEPaperMain(mainid, this.LanguageID);

            if (maindata.ID > 0) { ViewBag.ModelItemTitle = maindata.Name; }

            model = _service.GetModelByID(mainid, itemid, SET_EPAPER.M_EPAPER02);
            model.SET_EPAPER = SET_EPAPER;
            model.SET_BASE = SET_BASE;
            //model = _service.GetEPaperItemByID(itemid);
            return View("~/Areas/webadmin/Views/EPaper/EpaperEdit.cshtml", model);


        }

        //#region SaveItem
        public ActionResult SaveItem(EPaperEditModel model)
        {
            if (model.TopBannerImg != null)
            {
                model.TopBannerImgOrgName = model.TopBannerImg.FileName.Split('\\').Last();
                var root = Request.PhysicalApplicationPath;
                var newpath = root + "\\UploadImage\\EPaper\\";
                if (System.IO.Directory.Exists(newpath) == false)
                {
                    System.IO.Directory.CreateDirectory(newpath);
                }
                var guid = Guid.NewGuid();
                var filename = DateTime.Now.Ticks + "." + model.TopBannerImg.FileName.Split('.').Last();
                var path = newpath + filename;
                model.TopBannerImgName = filename;
                model.TopBannerImgPath = path;
                model.TopBannerImg.SaveAs(path);
            }

webadmin/Areas/webadmin/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Business;
using Oaww.Filter;
using Oaww.Entity.SET;
using Oaww.Entity;

namespace Template.webadmin.Areas.webadmin.Controllers
{
    public class ModelController : BaseController
    {
        CommonService _commonService = new CommonService();
        ModelService _service = new ModelService();

        [AuthFilter(_FuncionID = "Model/Index")]
        public ActionResult Index()
        {
            Session["menuNowID"] = 0;

            List<SET_MENU> ListSET_MENU = _commonService.GetGeneralList<SET_MENU>("M_Menu03=1").ToList();

            return View(ListSET_MENU);
        }

        /// <summary>
        /// 全文檢索管理
        /// </summary>
        /// <returns></returns>
        [AuthFilter(_FuncionID = "Model/IndexSetting")]
        public ActionResult IndexSetting()
        {
            Session["menuNowID"] = 0;

            var model = _service.GetPageIndexSetting(this.LanguageID);
            return View(model);
        }

        /// <summary>
        /// 全文檢索存檔
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [AjaxValidateAntiForgeryToken]
        public ActionResult SaveIndexSetting(PageIndexSetting model)
        {
            string result = _service.SetPageIndexSettingModel(model, this.LanguageID, this.Account);          

            return Content(result);
        }

        /// <summary>
        /// 照片上傳
        /// </summary>
        /// <param name="upload"></param>
        /// <param name="CKEditorFuncNum"></param>
        /// <param name="CKEditor"></param>
        /// <param name="langCode"></param>
        /// <returns></returns>
        public ActionResult Upload(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            var filename = "";
            var imageUrl = "";
            if (upload != null && upload.ContentLength > 0)
            {
                //儲存圖片至Server
                var last = upload.FileName.Split('.').Last();
                filename = DateTime.Now.Ticks + "." + last;
                var root = Request.PhysicalApplicationPath + "/UploadImage/PageIndex/";
                if (System.IO.Directory.Exists(root) == false)
                {
                    System.IO.Directory.CreateDirectory(root);
                }
                upload.SaveAs(root + filename);
                imageUrl = Url.Content((Request.ApplicationPath == "/" ? "" : Request.ApplicationPath) + "/UploadImage/PageIndex/" + filename);
                var vMessage = string.Empty;
                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";
            }
            return Json(new
            {
                uploaded = 1,
                fileName = filename,
                url = imageUrl
            });

        }

        public ActionResult UploadFile(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            var filename = "";
            var imageUrl = "";
            if (upload != null && upload.ContentLength > 0)
            {
                var last = upload.FileName.Split('.').Last();
                filename = DateTime.Now.Ticks + "." + last;
                var root = Request.PhysicalApplicationPath + "/UploadFile/PageIndex/";
                if (System.IO.Directory.Exists(root) == false)
                {
                    System.IO.Directory.CreateDirectory(root);
                }
                upload.SaveAs(root + filename);
                imageUrl = Url.Content((Request.ApplicationPath == "/" ? "" : Request.ApplicationPath) + "/UploadFile/PageIndex/" + filename);
                var vMessage = string.Empty;
                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";
            }
            return Json(new
            {
                uploaded = 1,
                fileName = filename,
                url = imageUrl
            });


        }
    }
}

webadmin/Areas/webadmin/Views/EPaper/EPaperContentMenu.cshtml
@model IEnumerable<Menu>
@Html.AntiForgeryToken()
<script src="@Url.Content("~/Scripts/components-date-time-pickers.min.js")"></script>
<script src="@Url.Content("~/Scripts/bootstrap-datepicker.min.js")"></script>
<script src="@Url.Content("~/Scripts/custom.js")"></script>
<script src="@Url.Content("~/Scripts/ckeditor/ckeditor.js")"></script>
<script src="@Url.Content("~/Scripts/bootbox.min.js")"></script>
@*<script src="//cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>*@
<!-- 載入 summernote 中文語系 -->
<!--page bar start-->
@{
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";
    IEnumerable<EPaperAutoItem> Itemlist = (IEnumerable<EPaperAutoItem>)ViewBag.ItemList;
}
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Model")">模組管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","EPaper")">電子報管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("ModelItem",new {mainid = ViewBag.mainid })">@ViewBag.ModelItemTitle 管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">@ViewBag.Title 管理</a>
        </li>
    </ul>

</div>
<!--page bar end-->
<!--message start-->
<h2>@ViewBag.Title</h2>

<div class="portlet light bordered">
    <div class="table-toolbar">
        <div class="col-md-12 col-sm-12 col-xs-12 mobile_left">
            <p class="display_inline">
                <button class="btn grey-mint" onclick="location.href='@Url.Action("ModelItem",new {mainid = ViewBag.mainid })'">回上一頁</button>
            </p>
        </div>
    </div>
    @using (Ajax.BeginForm("MainMenu", new AjaxOptions { UpdateTargetId = "eventtable" }))
    {
        <div class="table-scrollable" id="eventtable">
            <table class="table table-bordered competence_table" style="width:100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                    
                    @{
                        var l1arr = Model.Where(v => v.MenuLevel == 1);
                        foreach (var l1 in l1arr)
                        {
                            var l2arr = Model.Where(v => v.ParentID == l1.ID).ToArray();
                            if (ViewBag.onlylevle1 == "Y")
                            {
                                l2arr = new Menu[] { };
                            }
                            var l1rowcount = 0;
                            var arrl2stratidx = new List<int>();
                            var l3useidx = 0;
                            foreach (var l2 in l2arr)
                            {
                                var l3cnt = Model.Where(v => v.ParentID == l2.ID).Count();
                                arrl2stratidx.Add(l1rowcount);
                                l1rowcount += Math.Max(1, l3cnt);
                            }
                            l1rowcount = l1rowcount == 0 ? 1 : l1rowcount;
                            IList<Menu> _l3menu = null;
                            for (var idx = 0; idx < l1rowcount; idx++)
                            {
                                <tr>
                                    @if (idx == 0)
                                    {
                                        <td class='class_03' rowspan='@l1rowcount'>
                                            <div class='display_inline' style='float:left'>
                                                @if (l1.ModelID == 2)
                                                {
                                                    <button type='button' class='btn blue edit' index='@l1.ID' style='float:left; margin-left:2px'>選擇</button>
                                                }
                                            </div>
                                            <div class='training_class_title' style='float:left; margin-left:10px' level='@l1.MenuLevel'>@l1.MenuName</div>
                                        </td>
                                        if (l2arr.Count() == 0)
                                        {
                                            <td class='class_03'>&nbsp;</td>
                                            <td class='class_03'>&nbsp;</td>
                                        }
                                    }
                                    @if (arrl2stratidx.Contains(idx))
                                    {
                                        var l2arridx = arrl2stratidx.IndexOf(idx);
                                        if (l2arridx >= l2arr.Count())
                                        {
                                            <td class='class_03'>&nbsp;</td>
                                        }
                                        else
                                        {
                                            _l3menu = Model.Where(v => v.ParentID == @l2arr[l2arridx].ID).ToArray();
                                            l3useidx = 0;
                                            <td class='class_03' rowspan='@(_l3menu.Count()==0?1:_l3menu.Count())'>
                                                <div class='display_inline' style='float:left'>
                                                    @if (@l2arr[l2arridx].ModelID == 2)
                                                    {
                                                        <button type='button' class='btn blue edit' index='@l2arr[l2arridx].ID' style='float:left; margin-left:2px'>選擇</button>
                                                    }
                                                </div>
                                                <div class='training_class_title' style='float:left; margin-left:10px' level='@l2arr[l2arridx].MenuLevel'>@l2arr[l2arridx].MenuName</div>
                                            </td>
                                            if (_l3menu.Count() == 0)
                                            {
                                                <td class='class_03'>&nbsp;</td>
                                            }
                                        }
                                    }

                                    @if (_l3menu != null && l3useidx < _l3menu.Count())
                                    {
                                        <td class='class_03'>
                                            <div class='display_inline' style='float:left'>
                                                @if (@_l3menu[l3useidx].ModelID == 2)
                                                {
                                                    <button type='button' class='btn blue edit' index='@_l3menu[l3useidx].ID' style='float:left; margin-left:2px'>選擇</button>
                                                }
                                            </div>
                                            <div class='training_class_title' style='float:left; margin-left:10px' level='@_l3menu[l3useidx].MenuLevel'>@_l3menu[l3useidx].MenuName</div>
                                        </td>
                                        l3useidx += 1;
                                    }
                                </tr>
                            }
                        }
                    }

                </tbody>
            </table>
        </div>
     }
</div>
@section scripts {
    <script>
        $(function () {
        	$(".edit").click(function () {
                var obj = {};
                //menuid = 
                obj.menuid = $(this).attr("index");
                obj.id = '@ViewBag.ID';
                obj.mainid = '@ViewBag.mainid';
				CreatePost('@Url.Action("EPaperItemSelect")', obj);
            });
        });
    </script>
}

webadmin/Areas/webadmin/Views/EPaper/EPaperManuallyContent.cshtml
<script src="@Url.Content("~/Scripts/components-date-time-pickers.min.js")"></script>
<script src="@Url.Content("~/Scripts/bootstrap-datepicker.min.js")"></script>
<script src="@Url.Content("~/Scripts/custom.js")"></script>
<script src="@Url.Content("~/Scripts/ckeditor/ckeditor.js")"></script>
<script src="@Url.Content("~/Scripts/bootbox.min.js")"></script>
@*<script src="//cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>*@
<!-- 載入 summernote 中文語系 -->
@{
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";
}

<!--page bar start-->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Model")">模組管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","EPaper")">電子報管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("ModelItem",new {mainid = ViewBag.mainid })">@ViewBag.ModelItemTitle 管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">@ViewBag.Title 管理</a>
        </li>
    </ul>

</div>
<!--page bar end-->
<!--message start-->
<h2>@ViewBag.Title</h2>

<div class="portlet light bordered">
    <form class="form-horizontal form-bordered" method="Post" id="editform" action='@Url.Action("SaveManuallyContent")' enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <div class="portlet light form-fit bordered">
            <div class="portlet-body form">
                <div class="form-horizontal form-bordered">
                    <div class="form-body">
                        <div class="form-group">
                            <div class="col-md-2 col-sm-12 search_item">內容</div>
                            <div class="col-md-10 col-sm-12 bg-white mobile_white">
                                <textarea cols="80" id="HtmlContent" rows="20">@ViewBag.HtmlContent</textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center search_padding">
            <button type="submit" class="btn blue" id="btn_submit">確認送出</button>
            <button type="button" class="btn blue" id="btn_return" onclick="document.location.href='@Url.Action("ModelItem",new {mainid = ViewBag.mainid })'">返回列表</button>
        </div>
        <!--message end-->
    </form>
</div>
@section scripts {
    <script>
        $(function () {
               var ckedit = CKEDITOR.replace('HtmlContent', {
                height: 300,
               filebrowserImageUploadUrl: '@Url.Action("Upload")?command=QuickUpload&type=Images',
               filebrowserUploadUrl: '@Url.Action("UploadFile")?command=QuickUpload&type=Files',
            });
            CKEDITOR.config.enterMode = CKEDITOR.ENTER_BR;
            CKEDITOR.config.shiftEnterMode = CKEDITOR.ENTER_P;
            CKEDITOR.on('instanceReady', function (ev) {
                ev.editor.dataProcessor.writer.setRules('p',
                    {
                        indent: false,
                        breakBeforeOpen: false,
                        breakAfterOpen: false,
                        breakBeforeClose: false,
                        breakAfterClose: false
                    });
            });
            CKEDITOR.on('instanceReady', function (ev) {
                ev.editor.dataProcessor.writer.setRules('div',
                    {
                        indent: true,
                        breakBeforeOpen: true,
                        breakAfterOpen: true,
                        breakBeforeClose: false,
                        breakAfterClose: false
                    });
            });

            $('#editform').submit(function (event) {
                var formData = new FormData();
                formData.append("ID", '@ViewBag.ID');
                formData.append("HtmlContent", encodeURIComponent(CKEDITOR.instances.HtmlContent.getData()));
                $.ajax({
                    url: this.action,
                    data: formData,
                    type: 'POST',
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        alert(data);
                       CreatePost('@Url.Action("ModelItem",new {mainid = ViewBag.mainid })',null);
                    }, error: function () {
                        // handle error
                    }
                });
                return false;
            });
        });
    </script>
}

webadmin/Areas/webadmin/Views/EPaper/EPaperReview.cshtml
@{
    Layout = null;
}
@model EPaperEditModel
@Html.AntiForgeryToken()
<!DOCTYPE html>
<html lang="Zh-hant" xml:lang="Zh-hant">
<!--英文版<html lang="en" xml:lang="en">-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>中華穀類食品工業技術研究所</title><!--英文 China Grain Products research & Development Institute-->
    <link rel="icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="@Url.Content("~/css/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/theme.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/theme-elements.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/settings.css")" media="screen">

    <!--fontawesome start-->
    <link rel="stylesheet" href="@Url.Content("~/css/font-awesome.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/fontawesome.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/brands.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/solid.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/regular.min.css")">
    <!--fontawesome end-->

    <link rel="stylesheet" href="@Url.Content("~/css/style.css")">
    <script src="@Url.Content("~/js/jquery.js")"></script>
    <script src="@Url.Content("~/js/main.js")"></script>
    <noscript>
        <link rel="stylesheet" href="@Url.Content("~/css/noscript.css")">
    </noscript>


</head>

<body style="max-width:806px; margin:0 auto; font-family: 微軟正黑體, open-sans, Times New Roman , sans-serif;background: url(@Url.Content("~/Content/img/index_bg_news.png"));background-attachment: fixed; background-size: cover;">
    <div class="con_box">
        @if (string.IsNullOrEmpty(Model.TopBannerImgName) == false)
        {
            <div class="con_banner">
                <img src="@Model.TopBannerImgUrl" alt="" style="border-radius: 10px;box-shadow: 0px 0px 6px 2px rgba(20%,20%,20%,0.1);border: solid 1px #fff;" />
            </div><!--建議尺寸740*185px；後台未上傳圖片時show預設圖print_banner.jpg -->
        }
        else
        {
            <div class="con_banner">
                <img src="@Url.Content("~/Content/img/print_banner.jpg")" alt="" style="border-radius: 10px;box-shadow: 0px 0px 6px 2px rgba(20%,20%,20%,0.1);border: solid 1px #fff;width:100%" />
            </div><!--建議尺寸740*185px；後台未上傳圖片時show預設圖print_banner.jpg -->
        }
        <div class="date">《發佈日期：@Model.PublishStr》</div>
        <div class="title"><h2>@Model.Title </h2></div>
        @if (Model.PaperMode == 1)
        {
            @Html.Raw(Model.EPaperHtmlContent.safeHtmlFragment())
        }
        else
        {
            if (Model.EPaperItemEdit != null)
            {
                foreach (var items in Model.EPaperItemEdit)
                {
                    <div class="epaper_list">
                        <div class="epaper_class">@items.Name</div>
                        <ul class="epaper_item">
                            @for (var idx = 0; idx < items.ItemName.Count(); idx++)
                            {
                                <li><a href='@items.ItemUrl[idx]' target="_blank" title="@Html.Raw(items.ItemName[idx])">@Html.Raw(items.ItemName[idx])</a></li>
                            }
                        </ul>
                    </div>
                }
            }
        }
        <div style="text-align:center;font-size:0.8em;line-height:150%;border-top:double #fff 5px;float:left;width:100%;margin-top:10px;padding:10px;background:#f5f5f5;">@Html.Raw(Model.PageEndHtmlContent.safeHtmlFragment())</div>
    </div>
</body>
</html>