webadmin/Areas/webadmin/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Filter;
using Oaww.ViewModel;
using Oaww.ViewModel.Search;
using Oaww.Entity;
using Oaww.Entity.SET;
using Oaww.Business;
using Oaww.Utility;
using System.Configuration;
using System.IO;
using static Oaww.Business.CommonService;
using Newtonsoft.Json;

namespace Template.webadmin.Areas.webadmin.Controllers
{
    public class MessageController : BaseController
    {
        protected CommonService _commonService = new CommonService();
        MenuService _menuService = new MenuService();
        protected MessageService _service;
        protected SET_MESSAGE SET_MESSAGE = new SET_MESSAGE();
        protected int _ModelID = 2;
        private SET_BASE SET_BASE;
        private SET_MENU SET_MENU;
        protected List<SET_MESSAGE_ADD> SET_MESSAGE_ADDs;
        SiteConfigService _siteConfigService = new SiteConfigService();
        public MessageController()
        {
            SET_MESSAGE = _commonService.GetGeneral<SET_MESSAGE>("M_MESSAGE01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } });
            _service = new MessageService(_ModelID);
            SET_BASE = _commonService.GetGeneral<SET_BASE>();
            SET_MENU = _commonService.GetGeneral<SET_MENU>("M_Menu01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } });
            SET_MESSAGE_ADDs = _commonService.GetGeneralList<SET_MESSAGE_ADD>("M_MESSAGE_ADD01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } }).ToList();
        }
        public MessageController(int ModelID = 2)
        {
            SET_MESSAGE = _commonService.GetGeneral<SET_MESSAGE>("M_MESSAGE01=@ID", new Dictionary<string, string>() { { "ID", ModelID.ToString() } });
            _service = new MessageService(ModelID);
            _ModelID = ModelID;
            SET_BASE = _commonService.GetGeneral<SET_BASE>();
            SET_MENU = _commonService.GetGeneral<SET_MENU>("M_Menu01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } });
            SET_MESSAGE_ADDs = _commonService.GetGeneralList<SET_MESSAGE_ADD>("M_MESSAGE_ADD01=@ID", new Dictionary<string, string>() { { "ID", _ModelID.ToString() } }).ToList();
        }

        #region Grid
        [AuthFilter(_FuncionID = "Model/Index")]
        public ActionResult Index()
        {
            ViewBag.Title = SET_MESSAGE.M_MESSAGE05;
            ViewBag.Link = SET_MESSAGE.M_MESSAGE06;
            return View("~/Areas/webadmin/Views/Message/Index.cshtml");
        }

        /// <summary>
        /// Grid Data
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult PagingMain(SearchModelBase model)
        {
            model.LangId = this.LanguageID;
            return Json(_service.Paging(model, _ModelID));
        }

        /// <summary>
        /// update seq
        /// </summary>
        /// <param name="id"></param>
        /// <param name="seq"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult EditSeq(int? id, int seq, string type)
        {
            ModelMessageMain modelAMLMain = _service.GetModelMessageMain(id.ToString(), this.LanguageID);

            string result = _commonService.UpdateSeq<ModelMessageMain>(id.Value, seq, this.LanguageID, this.Account, this.UserName, _ModelID);

            
            return Json(result);
        }

        /// <summary>
        /// 刪除資料
        /// </summary>
        /// <param name="idlist"></param>
        /// <param name="delaccount"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SetMainDelete(string[] idlist, string delaccount)
        {
            List<MessageItem> messageItems = _service.GetMessageItemsByModelID(idlist);

            string result = _service.Delete(idlist, delaccount, this.LanguageID, this.Account, this.UserName);

            if (result == "刪除成功")
            {
                var oldroot = System.Web.HttpContext.Current.Request.PhysicalApplicationPath + $"\\UploadImage\\{SET_MESSAGE.M_MESSAGE02}\\";

                foreach (var items in messageItems)
                {
                    _commonService.InsertLog(Operation.Delete, this.Account, items.ModelName,"",
                     "MainMessage"
                     , ""
                     , "");
                    //刪除File
                    if (items.UploadFileName.IsNullOrEmpty() == false)
                    {
                        items.UploadFilePath = System.Web.HttpContext.Current.Request.PhysicalApplicationPath + "\\UploadFile" + items.UploadFilePath;

                        if (System.IO.File.Exists(items.UploadFilePath))
                        {
                            System.IO.File.Delete(items.UploadFilePath);
                        }
                    }
                    if (items.ImageFileName.IsNullOrEmpty() == false)
                    {

                        if (System.IO.File.Exists(oldroot + "\\" + items.ImageFileName))
                        {
                            System.IO.File.Delete(oldroot + "\\" + items.ImageFileName);
                        }
                    }

                    if (items.RelateImageFileName.IsNullOrEmpty() == false)
                    {

                        if (System.IO.File.Exists(oldroot + "\\" + items.RelateImageFileName))
                        {
                            System.IO.File.Delete(oldroot + "\\" + items.RelateImageFileName);
                        }
                    }
                }


            }

            return Content(result);
        }

        /// <summary>
        /// 新增刪除Unit
        /// </summary>
        /// <param name="mainid"></param>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult EditUnit(string mainid, string name)
        {

            var str = "";
            var rest = string.Empty;
            rest = GetMinModel(_ModelID);
            if (mainid == "-1" || string.IsNullOrEmpty(mainid))
            {


                str = _menuService.AddUnit<ModelMessageMain>(name, this.LanguageID, this.Account, _ModelID) ? "新增成功" : "新增失敗";
               if(str== "新增成功")
                {
                    _commonService.InsertLog(Operation.Insert, this.Account, name, "",
                     $"{rest}"
                     , ""
                     ,$"新增訊息單元名稱:{name}");
                }

            }
            else
            {
                string odatName = _service.GetModelMessageMain(mainid, this.LanguageID).Name;
                str = _menuService.UpdateUnit<ModelMessageMain>(name, mainid, this.Account, _ModelID.ToString()) ? "修改成功" : "修改失敗";
                if (str == "修改成功")
                {
                 _commonService.InsertLog(Operation.Update, this.Account, odatName
                   ,""
                   , $"{rest}"
                   , $"原訊息單元名稱:{odatName}  ItemID:{mainid}"
                   , $"修改過後訊息單元名稱:{name}");
                }
            }
            return Json(str);

        }

        #endregion

        #region Item Page
        /// <summary>
        /// Model Item List
        /// </summary>
        /// <param name="mainid"></param>
        /// <param name="menuindex"></param>
        /// <returns></returns>
        public ActionResult ModelItem(string mainid, string menuindex, bool admin = false)
        {
            mainid = mainid.AntiXss();

            if (mainid.IsNullOrEmpty()) { return RedirectToAction("Index"); }


            var grouplist = _commonService.GetAllGroupSelectList<GroupMessage>(mainid);
            grouplist.Insert(0, new System.Web.Mvc.SelectListItem() { Text = "全部", Value = "" });
            ViewBag.grouplist = grouplist;
            ViewBag.mainid = mainid.AntiXss();
            ViewBag.admin = admin;
            var maindata = _service.GetModelMessageMain(mainid, this.LanguageID);

            if (maindata.ID > 0) { ViewBag.Title = maindata.Name; }

            ViewBag.SET_BASE = SET_BASE;
            ViewBag.SET_MENU = SET_MENU;
            ViewBag.SET_MESSAGE = SET_MESSAGE;
            ViewBag.SET_MESSAGE_ADDs = SET_MESSAGE_ADDs;

            return View("~/Areas/webadmin/Views/Message/ModelItem.cshtml");
        }

        public ActionResult PagingItem(MessageSearchModel model)
        {
            return Json(_service.PagingItem(model.ModelID.ToString(), model, this.LanguageID));
        }

        public ActionResult MessageEdit(string mainid, string itemid = "-1")
        {
            ViewBag.isview = Request["isview"] == null ? "" : Request["isview"].ToString().AntiXss();
            if (mainid.IsNullOrEmpty()) { return RedirectToAction("Index"); }

            ViewBag.grouplist = _commonService.GetAllGroupSelectList<GroupMessage>(mainid);
            MessageEditModel model = null;
            model = _service.GetModelByID(mainid, itemid, SET_MESSAGE.M_MESSAGE02);
            model.Link_Mode = model.Link_Mode.HasValue ? model.Link_Mode.Value : 1;
            model.SET_MESSAGE = SET_MESSAGE;
            model.SET_BASE = SET_BASE;

            return View("~/Areas/webadmin/Views/Message/MessageEdit.cshtml", model);
        }

        public ActionResult SaveItem(MessageEditModel model)
        {
            var uploadfilepath = ConfigurationManager.AppSettings["UploadFile"];
            SiteConfig ListConfig = _siteConfigService.GetALLSiteConfig("1");
            if (uploadfilepath.IsNullOrEmpty())
            {
                uploadfilepath = Request.PhysicalApplicationPath + "\\UploadFile";
            }
            if (model.fileDownloadFiles != null)
            {
                int i = 0;
                model.fileDownloadFiles.ForEach(t =>
                {
                    if (t.UploadFile != null)
                    {

webadmin/Areas/webadmin/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oaww.Business;
using Oaww.Filter;
using Oaww.Entity.SET;
using Oaww.Entity;

namespace Template.webadmin.Areas.webadmin.Controllers
{
    public class ModelController : BaseController
    {
        CommonService _commonService = new CommonService();
        ModelService _service = new ModelService();

        [AuthFilter(_FuncionID = "Model/Index")]
        public ActionResult Index()
        {
            Session["menuNowID"] = 0;

            List<SET_MENU> ListSET_MENU = _commonService.GetGeneralList<SET_MENU>("M_Menu03=1").ToList();

            return View(ListSET_MENU);
        }

        /// <summary>
        /// 全文檢索管理
        /// </summary>
        /// <returns></returns>
        [AuthFilter(_FuncionID = "Model/IndexSetting")]
        public ActionResult IndexSetting()
        {
            Session["menuNowID"] = 0;

            var model = _service.GetPageIndexSetting(this.LanguageID);
            return View(model);
        }

        /// <summary>
        /// 全文檢索存檔
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [AjaxValidateAntiForgeryToken]
        public ActionResult SaveIndexSetting(PageIndexSetting model)
        {
            string result = _service.SetPageIndexSettingModel(model, this.LanguageID, this.Account);          

            return Content(result);
        }

        /// <summary>
        /// 照片上傳
        /// </summary>
        /// <param name="upload"></param>
        /// <param name="CKEditorFuncNum"></param>
        /// <param name="CKEditor"></param>
        /// <param name="langCode"></param>
        /// <returns></returns>
        public ActionResult Upload(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            var filename = "";
            var imageUrl = "";
            if (upload != null && upload.ContentLength > 0)
            {
                //儲存圖片至Server
                var last = upload.FileName.Split('.').Last();
                filename = DateTime.Now.Ticks + "." + last;
                var root = Request.PhysicalApplicationPath + "/UploadImage/PageIndex/";
                if (System.IO.Directory.Exists(root) == false)
                {
                    System.IO.Directory.CreateDirectory(root);
                }
                upload.SaveAs(root + filename);
                imageUrl = Url.Content((Request.ApplicationPath == "/" ? "" : Request.ApplicationPath) + "/UploadImage/PageIndex/" + filename);
                var vMessage = string.Empty;
                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";
            }
            return Json(new
            {
                uploaded = 1,
                fileName = filename,
                url = imageUrl
            });

        }

        public ActionResult UploadFile(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            var filename = "";
            var imageUrl = "";
            if (upload != null && upload.ContentLength > 0)
            {
                var last = upload.FileName.Split('.').Last();
                filename = DateTime.Now.Ticks + "." + last;
                var root = Request.PhysicalApplicationPath + "/UploadFile/PageIndex/";
                if (System.IO.Directory.Exists(root) == false)
                {
                    System.IO.Directory.CreateDirectory(root);
                }
                upload.SaveAs(root + filename);
                imageUrl = Url.Content((Request.ApplicationPath == "/" ? "" : Request.ApplicationPath) + "/UploadFile/PageIndex/" + filename);
                var vMessage = string.Empty;
                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";
            }
            return Json(new
            {
                uploaded = 1,
                fileName = filename,
                url = imageUrl
            });


        }
    }
}

webadmin/Areas/webadmin/Views/Message/GroupEdit.cshtml
@{
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/datatable.js"></script>
<script src="~/Scripts/custom.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
<!--page bar start-->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action(" Index","Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action(" Index","Model")">模組元件</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action(" Index","Message")">訊息管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("ModelItem","Message",new { mainid=ViewBag.mainid })">清單</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">類別管理</a>
        </li>
    </ul>

</div>
<!--page bar end-->
<div class="title_01"> 類別管理設定</div>
<div class="portlet light bordered">
    <!--set item start-->
    <div class="table-toolbar">
        <div class="col-md-6 col-sm-12 col-xs-12 mobile_left ">
        </div>
        <div class="col-md-6 col-sm-12 col-xs-12 mobile_left ">
            <p class="display_inline ">
                <button class="btn green-meadow" id='btn_add'>新增 <i class="fa fa-plus"></i></button>
                <button type="button" class="btn blue" id="btn_return">返回</button>
            </p>
        </div>
    </div>
    <!--set item end-->
    <!--table start-->
    <div class="table-scrollable">
        <table class="table table-bordered table-hover" border="0" cellspacing="0" cellpadding="0" style="width:500px"
               id="eventtable"
               data-url="@Url.Action("PagingGroup")"
               data-sort-name='Sort'
               data-page-size='10'
               data-filed-id='ID'
               data-max-pagination='10'>
            <thead>
                <tr class="bg-grey_1" filed-class='odd gradeX'>
                    <th width="80px" class="text-center" filed-type='delcheckbox'>
                        <label class='mt-checkbox mt-checkbox-single mt-checkbox-outline'>
                            <input type='checkbox' class='checkboxes' id="chk_all" /><span></span>
                        </label>
                        <button class="btn red-mint btn-xs" id='btn_del'><i class="glyphicon glyphicon-trash"></i></button>
                    </th>
                    <th filed-name='Sort' width="160px" class="text-center" filed-type='numbertextcheck' filed-item-class="sortedit">排序</th>
                    <th filed-name='Group_Name' class="text-center" filed-type='link'>類別名稱</th>
                    <th width="80px" filed-name='Enabled' class="text-center" filed-type='checkbox' filed-item-class="chkstatus">顯示</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div id="page_number" class="table-toolbar">
        <div class="col-md-4 col-sm-12 col-xs-12 page_total" id="tableinfo"></div>
        <div class="col-md-8 col-sm-12 col-xs-12 page_icon">
            <div class="btn-group" id="pagination">
            </div>
        </div>
    </div>
    <!--table end-->

</div>
<!--message end-->
@section scripts {
    <script>
    var selvalue = [];
    $(document).ready(function () {
        mytable = $("#eventtable").myDataTable().TableList[0];
        mytable.settingTdData = myDataTableTr;
        mytable.settingTableInfo = function (tableinfoId, totalcnt, offsetcnt, nowpagecnt) {
            var totalclick = mytable.keepcheckid.length;
            $("#" + tableinfoId).html('總筆數:' + totalcnt + '，顯示' + (totalcnt <= 0 ? 0 : offsetcnt) + "~" + (offsetcnt + nowpagecnt - 1));
        };
        mytable.SearchModelBase.ModelID = '@ViewBag.mainid';
        mytable.GetData(1);
        var obj = {};
        obj.item = "類別";
        obj.mainid = '@ViewBag.mainid';
        RegisterOrder("#eventtable", ".sortedit", '@Url.Action("EditGroupSeq")', obj);
        RegisterClickAll("#chk_all", '#eventtable tbody .chksel', "#selvalue");
        RegisterDelete("#btn_del", '#eventtable .chksel:checked', '@Url.Action("SetGroupDelete")', obj);
        RegisterClicklink("#eventtable", ".edit", '@Url.Action("EditGroup")', obj, 'UpdateItem');
        RegisterClicklink("#eventtable", ".manage", '@Url.Action("ModelItem")', obj);
        RegisterClick("#eventtable", ".chkstatus", '@Url.Action("SetGroupStatus")', obj);
        $("#btn_add").click(function () { CallAddDialog('@Url.Action("EditGroup")', obj); });
        $("#btn_return").click(function () {
            CreatePost('@Url.Action("ModelItem")', { mainid: '@ViewBag.mainid' });
        });
    });
    </script>
}

webadmin/Areas/webadmin/Views/Message/Index.cshtml
@{
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";
}
<!--page bar start-->
<div class="page-bar all_width">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Model")">模組管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">訊息管理</a>
        </li>
    </ul>
</div>
<!--page bar end-->
<div class="title_01">@ViewBag.Title</div>
<div class="portlet light bordered">
    <!--set item start-->
    <div class="table-toolbar">
        <div class="col-md-6 col-sm-12 col-xs-12">

        </div>
        <div class="col-md-6 col-sm-12 col-xs-12 mobile_left">
            <p class="display_inline">
                <button class="btn green-meadow" id='btn_add'>新增 <i class="fa fa-plus"></i></button>
            </p>
        </div>
    </div>
    <div class="table-scrollable">
        <table class="table table-bordered table-hover" border="0" cellspacing="0" cellpadding="0"
               id="eventtable"
               data-url="@Url.Action("PagingMain")"
               data-sort-name='Sort'
               data-page-size='10'
               data-filed-id='ID'
               data-max-pagination='10'>
            <thead>
                <tr class="bg-grey_1" filed-class='odd gradeX'>
                    <th width="80" class="text-center delete_th" filed-type='delcheckbox'>
                        <label class='mt-checkbox mt-checkbox-single mt-checkbox-outline'>
                            <input type='checkbox' class='checkboxes' id="chk_all" /><span></span>
                        </label>
                        <button class="btn red-mint btn-xs" id='btn_del'><i class="glyphicon glyphicon-trash"></i></button>
                    </th>
                    <th filed-name='Sort' width="160px" class="text-center" filed-type='numbertextcheck' filed-item-class="sortedit">排序</th>
                    <th filed-name='Name' class="text-center" filed-type='link'>單元名稱</th>
                    <th filed-name='customertr' width="350px" class="text-center" filed-type='function'>單元路徑</th>
                    <th filed-name='管理' width="80px" class="text-center" filed-type='button' filed-item-class="btn grey-mint manage">管理</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    <div id="page_number" class="table-toolbar">
        <div class="col-md-4 col-sm-12 col-xs-12 page_total" id="tableinfo"></div>
        <div class="col-md-8 col-sm-12 col-xs-12 page_icon">
            <div class="btn-group" id="pagination">
            </div>
        </div>
    </div>
    <!--table end-->
</div>

<!--message end-->
@section scripts {
    <script src="@Url.Content("~/Scripts/datatable.js")"></script>
    <script src="@Url.Content("~/Scripts/custom.js")"></script>
    <script src="@Url.Content("~/Scripts/bootbox.min.js")"></script>
    <script src="@Url.Content("~/Scripts/clipboard.min.js")"></script>
    <script>
        $(document).ready(function () {
            mytable = $("#eventtable").myDataTable().TableList[0];
            mytable.settingTdData = myDataTableTr;
            mytable.settingTableInfo = function (tableinfoId, totalcnt, offsetcnt, nowpagecnt) {
                var totalclick = mytable.keepcheckid.length;
                $("#" + tableinfoId).html('總筆數:' + totalcnt + '，顯示' + (totalcnt <= 0 ? 0 : offsetcnt) + "~" + (offsetcnt + nowpagecnt - 1));
            };
            var SearchModelBase = mytable.SearchModelBase;
            mytable.GetData(1);
            var obj = {};
            obj.idkey ="mainid"
            obj.item = "單元名稱";
            RegisterOrder("#eventtable", ".sortedit", '@Url.Action("EditSeq")', obj);
            RegisterClickAll("#chk_all", '#eventtable tbody .chksel', "#selvalue");
            RegisterDelete("#btn_del", '#eventtable .chksel:checked', '@Url.Action("SetMainDelete")', obj);
            RegisterClicklink("#eventtable", ".edit", '@Url.Action("EditUnit")', obj, 'UpdateItem');
            RegisterClicklink("#eventtable", ".manage", '@Url.Action("ModelItem")', obj,"mainid");

            $("#btn_add").click(function () { CallAddDialog('@Url.Action("EditUnit")', { mainid: -1 ,item : "單元名稱"}); });
            var clipboard = new Clipboard('.btn', {
                text: function (event) {
                    return $(event).attr('copy');
                }
            });
        });
        function customertr(row, columnidx, idx, filedname, tableid, type, fileditemclass) {
            return "<td><input  type='text' readonly=readonly style='width:250px; display:inline' class='form-control' value='@(ViewBag.Link)/Index?itemid=" + row[tableid] + "'/><button class='btn grey-mint' style='margin-left:20px' copy='Message/Index?itemid=" + row[tableid] + "'>複製</button></td>";
        }
    </script>
}